org.gradle.jvmargs=-Xmx1280m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=1
org.gradle.daemon=false

android.useAndroidX=true
android.nonTransitiveRClass=true
# اجرای dex در همان پروسه برای مصرف کمتر حافظه در ماشین‌های کم‌رم
android.enableR8.fullMode=false

kotlin.code.style=official
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx1024m
